Taller/Taller.App.Front/Pages/Cuenta/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages
{
    public class LoginModel : PageModel
    {

        public string tituLogin { get; set; }

        public void OnGet()
        {
            tituLogin = $" Server time is {DateTime.Now}";
        }
    }
}

Taller/Taller.App.Front/Pages/Cuenta/Registro.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages
{
    public class RegistroModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Taller/Taller.App.Front/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Taller/Taller.App.Front/Pages/GestionMecanico/GestionMecanico.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Dominio;
using Taller.App.Persistencia;

namespace Taller.App.Front.Pages
{
    public class GestionMecanicoModel : PageModel
    {

        private static RepositorioMecanico repositorio = new RepositorioMecanico(
             new Persistencia.ContextDb()
        );


        public IEnumerable<Mecanico> listaMecanicos;
        public Mecanico mecanicoActual;

        public bool modeEdition = false;

        public string textBuscar;

        public void OnGet()
        {
            this.ObtenerMecanicos();
        }

        public void OnPostAdd(Mecanico mecanico)
        {
            // Console.WriteLine("Mecanico:" + mecanico.nivelEstudio);

            repositorio.AgregarMecanico(mecanico);
            this.ObtenerMecanicos();
        }


        public void OnPostBuscar(string textBuscar)
        {
            Console.WriteLine("OnPostBuscar:" + textBuscar);
            this.textBuscar = textBuscar;
            this.listaMecanicos = (IEnumerable<Mecanico>)repositorio.BuscarMecanicoNombre(textBuscar);
        }


        public void OnPostSelectEdit(string id)
        {
            if (id != null)
            {
                this.mecanicoActual = repositorio.BuscarMecanico(id);
                Console.WriteLine("edit" + this.mecanicoActual.Nombre);
                this.modeEdition = true;
            }
            this.ObtenerMecanicos();
        }

        public void OnPostDel(string id)
        {
            if (id != null)
            {
                repositorio.EliminarMecanico(id);
                this.ObtenerMecanicos();
            }
        }

        public void OnPostEdit(Mecanico mecanico)
        {
            repositorio.EditarMecanico(mecanico);
            this.ObtenerMecanicos();
        }

        public void ObtenerMecanicos()
        {
            this.listaMecanicos = (IEnumerable<Mecanico>)repositorio.ObtenerMecanicos();
        }

        // public async Task<IActionResult> OnPostAsync(Mecanic m)
        // {
        //     if (!ModelState.IsValid)
        //     {
        //         return Page();
        //     }

        //     if (Customer != null) _context.Customer.Add(Customer);
        //     await _context.SaveChangesAsync();

        //     return RedirectToPage("./Index");
        // }
    }

}

Taller/Taller.App.Front/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Taller/Taller.App.Front/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}


Taller/Taller.App.Front/Pages/Cuenta/Login.cshtml
@page
@model Taller.App.Front.Pages.LoginModel
@{
}

<div class="card clsCard" style="width: 18rem">
    <div class="card-body">
        <h1 id="idTituloLogin">@Model.tituLogin</h1>
        <div id="idContenedorCampos">
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Usuario</label>
                <input type="email" class="form-control" id="idUsuario" placeholder="name@example.com" />
            </div>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">contraseña</label>
                <input type="password" class="form-control" id="idContrasenia" />
            </div>
        </div>
        <button type="button" onclick="mostrarInformacion()" class="btn btn-info">
            Iniciar sesión
        </button>
    </div>
</div>

Taller/Taller.App.Front/Pages/Cuenta/Registro.cshtml
@page
@model Taller.App.Front.Pages.RegistroModel
@{
}

Taller/Taller.App.Front/Pages/GestionMecanico/GestionMecanico.cshtml
@page
@model Taller.App.Front.Pages.GestionMecanicoModel
@{
}

<div class="clas-contain-title d-flex justify-content-between">

    <div style="display: flex; align-items: center;">
        <h6 class="mb-0 me-3">Mecánicos</h6>
        <i class="bi bi-person-plus clas-icon-add" title="Agregar mecánico" data-bs-toggle="modal"
            data-bs-target="#exampleModal" data-bs-whatever="@@mdo"></i>
    </div>


    <nav class="navbar navbar-light">
        <form method="post" class="form-inline" style="display: flex;">
            <input name="textBuscar" class="form-control mr-sm-2" type="search" placeholder="Escribe aquí"
                aria-label="Search" asp-for="@Model.textBuscar">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-page-handler="Buscar">Buscar</button>
        </form>
    </nav>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Teléfono</th>
            <th scope="col" class="text-end">Acciones</th>
        </tr>
    </thead>
    <tbody>


        @foreach (var m in Model.listaMecanicos)
        {
            <tr>
                <td>@m.MecanicoId</td>
                <td>@m.Nombre</td>
                <td>@m.Telefono</td>
                <td class="text-end" style="display: flex; justify-content: flex-end;">

                    @if (@Model.mecanicoActual != null && @Model.mecanicoActual.MecanicoId != "")
                    {

                        <button class="bi bi-pencil-square class-icon-edit clas-no-sty-button" title="Editar mecánico"
                    id="idmodal" data-bs-toggle="modal" data-bs-target="#exampleModal"
                    data-bs-whatever="@@mdo"></button>
                    }
                    else
                    {
                        <form method="POST">

                            <button class="bi bi-pencil-square class-icon-edit clas-no-sty-button" title="Editar mecánico"
                        type="submit" asp-route-id="@m.MecanicoId" asp-page-handler="SelectEdit"></button>
                        </form>

                    }

                    <form method="POST">
                        <button class="bi bi-trash-fill class-icon-delete clas-no-sty-button" title="Eliminar mecánico"
                        type="submit" asp-route-id="@m.MecanicoId" asp-page-handler="Del"></button>
                    </form>



                </td>
            </tr>
        }

    </tbody>
</table>


<div class="column col-md-4">
    <label for="">Mecanico a asignar:</label>
    <select class="form-select" aria-label="Default select example" name="MecanicoId">
        @foreach (var m in Model.listaMecanicos)
        {
            <option value="@m.MecanicoId">@m.Nombre</option>
        }
    </select>
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                @if (@Model.modeEdition)
                {
                    <h5 class="modal-title" id="exampleModalLabel">Editar mécanico</h5>
                }
                else
                {
                    <h5 class="modal-title" id="exampleModalLabel">Agregar mecánico</h5>
                }

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="px-4" method="POST">

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="recipient-name" class="col-form-label">Id:</label>
                            <input type="text" class="form-control" id="recipient-name"
                                asp-for="@Model.mecanicoActual.MecanicoId" name="MecanicoId">
                        </div>
                        <div class="mb-3 col-6">
                            <label for="recipient-name" class="col-form-label">Nombre:</label>
                            <input type="text" class="form-control" id="recipient-name"
                                asp-for="@Model.mecanicoActual.Nombre" name="Nombre">
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="recipient-name" class="col-form-label"> Teléfono:</label>
                            <input type="tel" class="form-control" id="recipient-name"
                                asp-for="@Model.mecanicoActual.Telefono" name="Telefono">
                        </div>
                        <div class="mb-3 col-6">
                            <label for="recipient-name" class="col-form-label">Fecha nacimiento:</label>
                            <input type="date" class="form-control" id="recipient-name"
                                asp-for="@Model.mecanicoActual.FechaNacimiento" name="FechaNacimiento">
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-6">
                            <label for="recipient-name" class="col-form-label">Dirección:</label>
                            <input type="text" class="form-control" id="recipient-name"
                                asp-for="@Model.mecanicoActual.Direccion" name="Direccion">
                        </div>
                        <div class="mb-3 col-6">
                            <label for="recipient-name" class="col-form-label">Nivel de estudio:</label>
                            <select name="" id="" class="form-select" asp-for="@Model.mecanicoActual" NivelEstudio"
                                name="NivelEstudio">
                                <option value="Bachiller">Bachiller</option>
                                <option value="Técnico">Técnico</option>
                                <option value="Tecnólogo">Tecnólogo</option>
                                <option value="Profesional">Profesional</option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="mb-3 col-12">
                            <label for="recipient-name" class="col-form-label">Contraseña:</label>
                            <input type="password" class="form-control" id="recipient-name"
                                asp-for="@Model.mecanicoActual.Contrasenia" name="Contrasenia">
                        </div>


                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>

                        @if (@Model.modeEdition)
                        {
                            <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Editar</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary" asp-page-handler="Add">Agregar</button>
                        }


                    </div>

                </form>
            </div>

        </div>
    </div>
</div>


@if (@Model.modeEdition)
{
    <script type="text/javascript">

    setTimeout(() => {
        let button = document.getElementById("idmodal");
        button.click();
    }, 500);
</script>
}

Taller/Taller.App.Front/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Taller/Taller.App.Front/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taller.App.Front</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Taller.App.Front.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-page="/Index">Taller G9</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cuenta/Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cuenta/Registro">Registro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                                asp-page="/GestionMecanico/GestionMecanico">Mecánicos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Taller.App.Front - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>